### ISSUE TITLE
missing files in data folder

### ISSUE THREAD

**Issue by zhaoedf** [GregoirePetit/FeTrIL#2]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/48846150/215956245-917c5704-cecb-4586-b1b3-0fa1f61e2b40.png">
when i ran the first command, this error occurred, it seems i need to put something in the data/features/... folder beforehand and i can not find any relevant information in your README.

**Comment by zhaoedf** [comment]
first command means
`
python codes/compute_distances.py configs/cifar100_b50_t10.cf
`

**Comment by GregoirePetit** [comment]
Hi,
Here you can find the updated [ReadMe](https://github.com/GregoirePetit/FeTrIL/blob/main/README.md#train-the-first-model-and-extract-the-features). Thank you for your comment :)
Grégoire

**Comment by vic-ene** [comment]
Hi,

After replacing the function get_dataset_mean_std as such to run on CIFAR100,

```
  def get_dataset_mean_std(self, normalization_dataset_name, datasets_mean_std_file_path):
      print(normalization_dataset_name, datasets_mean_std_file_path)
      if normalization_dataset_name == "cifar100":
          dataset_mean = (0.5071, 0.4867, 0.4408)
          dataset_std = (0.2675, 0.2565, 0.2761)
      return dataset_mean, dataset_std
```

I get the error File "/home/user/.conda/envs/fetril/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'data/list/cifar100/train.lst'

Could provide this file ?
I am unaware of such a file in cifar100 directory. 

Thanks in advance ! :)
