### ISSUE TITLE
FIleNotFoundError

### ISSUE THREAD

**Issue by kandeldeepak46** [GregoirePetit/FeTrIL#3]
![image](https://github.com/GregoirePetit/FeTrIL/assets/33603333/b6aa1383-b088-4f28-b269-81461204e43f)

Can somebody help to resolve this?

**Comment by george13zyx** [comment]
same problem

**Comment by GregoirePetit** [comment]
Replace by the path where the mean and std of the dataset are stored

**Comment by kandeldeepak46** [comment]
Hi Gregoire,

what is meant by the mean and std of cifar100? Could you please give details?

For other baselines, I believe, we don't have such parameters 

Thank you

**Comment by GregoirePetit** [comment]
No problem, I'm happy to help!
Computing the mean and the std is a very common practice in Continual Learning but also in Deep Learning in general: https://pytorch.org/vision/main/generated/torchvision.transforms.Normalize.html

It corresponds to the mean and the standard deviation per channel.

The goal is to give the network a normalized image, to avoid giving a too small or to large input.

Hope it answers your question.

**Comment by vic-ene** [comment]
Hi,

After replacing the function get_dataset_mean_std as such to run on CIFAR100,

```
  def get_dataset_mean_std(self, normalization_dataset_name, datasets_mean_std_file_path):
      print(normalization_dataset_name, datasets_mean_std_file_path)
      if normalization_dataset_name == "cifar100":
          dataset_mean = (0.5071, 0.4867, 0.4408)
          dataset_std = (0.2675, 0.2565, 0.2761)
      return dataset_mean, dataset_std
```

I get the error File "/home/user/.conda/envs/fetril/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'data/list/cifar100/train.lst'

Could you please provide this file ?
I am unaware of such a file in cifar100 directory. 

Thanks in advance ! :)

**Comment by GregoirePetit** [comment]
Hi,
As detailed in the readme, the FeTrIL repository depends on https://github.com/GregoirePetit/utilsCIL, which provides a link to the order in which classes the datasets are organized (for example, in the CIFAR100 case: https://github.com/GregoirePetit/imagelistsCIL/tree/master/cifar100). Also, everything works as it is. I advise you not to replace functions to make it run (see https://github.com/GregoirePetit/imagelistsCIL for organizing the data folder).
Best,
G. Petit
